# Generated by Django 4.1.4 on 2022-12-16 21:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fly_from', models.CharField(max_length=50)),
                ('fly_to', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('iata_city_from', models.CharField(max_length=3)),
                ('iata_port_from', models.CharField(max_length=3)),
                ('iata_city_to', models.CharField(max_length=3)),
                ('iata_port_to', models.CharField(max_length=3)),
                ('iata_stopovers', models.CharField(max_length=20)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('min_nights', models.IntegerField(max_length=3)),
                ('max_nights', models.IntegerField(max_length=3)),
                ('nights', models.IntegerField(max_length=3)),
                ('airlines', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
