# Generated by Django 4.1.4 on 2022-12-16 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_alter_flight_nights_alter_flight_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='nights',
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
