# Generated by Django 4.1.4 on 2022-12-17 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_alter_flight_nights'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='nights',
            field=models.IntegerField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='flight',
            name='price',
            field=models.IntegerField(blank=True, default=None),
        ),
    ]
