# Generated by Django 4.1.4 on 2022-12-17 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_alter_flight_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='nights',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='price',
            field=models.IntegerField(blank=True, default=9999999, null=True),
        ),
    ]
