# Generated by Django 4.1.4 on 2022-12-27 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_alter_flight_nights_alter_flight_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flight',
            name='title',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
