# Generated by Django 4.1.4 on 2023-01-14 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_alter_flightdetails_fly_from_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flightdetails',
            name='airlines',
        ),
        migrations.RemoveField(
            model_name='flightdetails',
            name='iata_stopovers',
        ),
        migrations.AddField(
            model_name='flightdetails',
            name='arrival_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flightdetails',
            name='departure_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='flightdetails',
            name='nights',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
