# Generated by Django 4.1.4 on 2023-01-14 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_remove_flightdetails_airlines_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightdetails',
            name='adults',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9)], null=True),
        ),
        migrations.AddField(
            model_name='flightdetails',
            name='max_sector_stopovers',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='flightdetails',
            name='stopover_from',
            field=models.CharField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20), (21, 21), (22, 22), (23, 23), (24, 24), (25, 25), (26, 26), (27, 27), (28, 28), (29, 29), (30, 30), (31, 31), (32, 32), (33, 33), (34, 34), (35, 35), (36, 36), (37, 37), (38, 38), (39, 39), (40, 40), (41, 41), (42, 42), (43, 43), (44, 44), (45, 45), (46, 46), (47, 47), (48, 48)], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='flightdetails',
            name='stopover_to',
            field=models.CharField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20), (21, 21), (22, 22), (23, 23), (24, 24), (25, 25), (26, 26), (27, 27), (28, 28), (29, 29), (30, 30), (31, 31), (32, 32), (33, 33), (34, 34), (35, 35), (36, 36), (37, 37), (38, 38), (39, 39), (40, 40), (41, 41), (42, 42), (43, 43), (44, 44), (45, 45), (46, 46), (47, 47), (48, 48)], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='flightdetails',
            name='from_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='flightdetails',
            name='iata_port_from',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='flightdetails',
            name='iata_port_to',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='flightdetails',
            name='max_nights',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='flightdetails',
            name='min_nights',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='flightdetails',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='flightdetails',
            name='to_date',
            field=models.DateField(null=True),
        ),
    ]
